# Generated by Django 4.0.4 on 2022-04-16 15:55

from django.db import migrations, models
import django.db.models.deletion
import tr069server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, validators=[tr069server.models.validate_ip])),
                ('customer_code', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('device', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='tr069server.device', to_field='ip')),
            ],
        ),
    ]
