# Generated by Django 4.0.4 on 2022-04-21 13:27

from django.db import migrations, models
import django.db.models.deletion
import tr069server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('ip', models.CharField(max_length=15, unique=True, validators=[tr069server.models.validate_ip])),
                ('customer_code', models.CharField(default='', max_length=256, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningStatus',
            fields=[
                ('device', models.OneToOneField(db_column='ip', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tr069server.device', to_field='ip')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
