# Generated by Django 4.0.4 on 2022-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr069server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='customer_code',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
